### ISSUE TITLE
missing 'Microsoft.SourceLink.GitHub' in project

### ISSUE THREAD

**Issue by Torchok19081986** [restsharp/RestSharp#1286] opened 2019-02-26 22:04 UTC
Hallo, i have a problem with Restharp V. 106.6 in some extra project. if i try add restsharp to my project and compiling it, vs 2017 says it not possible, because 'Microsoft.SourceLink.GitHub' are missing. NET Framework was set to 4.6.2 as target. Can someone help me pls ?

**Comment by tbladh** [comment] 2019-02-27 10:09
Same issue here. 

Ended up installing the source link beta manually from nuget package (Install-Package Microsoft.SourceLink.GitHub -Version 1.0.0-beta2-18618-05). This gets us a bit further but the build still fails with the message:

CS0016	Could not write to output file 'C:\Repos\GitHub\XXX\YYY\obj\Debug\YYY.sourcelink.json' -- 'Could not find file 'C:\Repos\GitHub\XXX\YYY\obj\Debug\YYY.sourcelink.json'.'	

Was targeting .NET 4.7.1.

Any ideas?

**Comment by Torchok19081986** [comment] 2019-02-27 10:59
Tried it. Could not find beta on link to beta.  Restsharp 105 was sucessfully insalled for .NET Framework 4.6.2.

**Comment by alexeyzimarev** [comment] 2019-02-27 11:14
Duplicate of #1285

**Comment by NXTwoThou** [comment] 2019-02-27 13:04
It's really a dupe of #1282 which a fix was committed 5 days ago.  Hopefully a new version will get pushed out soon so I can finally itch the "It says an update is available but I can't install it" spot.

**Comment by alexeyzimarev** [comment] 2019-02-27 20:21
Published in 106.8.9. The 106.8.8 is now unlisted.

**Closed by alexeyzimarev** 2019-02-27 20:21 UTC
