### ISSUE TITLE
Encoding  crash on 106.11.3

### ISSUE THREAD

**Issue by jorgenstorlie** [restsharp/RestSharp#1460] opened 2020-05-11 19:56 UTC
## Steps to Reproduce the Problem

I load some data like this:
 var restResponse = await ExecuteAsync(request, cancellationTokenSource).ConfigureAwait(false);

This crash on  106.11.3.
It works  106.11.2

## Specifications

  - Version: 106.11.3
  - Platform: iOS
  - Subsystem:

## StackTrace
<details>

Encoding 37 data could not be found. Make sure you have correct international codeset assembly installed and enabled. (System.NotSupportedException)
  at System.Text.Encoding.GetEncoding (System.Int32 codepage) [0x0021d] in /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/text/encoding.cs:553 
  at System.Text.EncodingInfo.GetEncoding () [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/src/Xamarin.iOS/external/corefx/src/Common/src/CoreLib/System/Text/EncodingInfo.cs:56 
  at RestSharp.Extensions.StringEncodingExtensions..cctor () [0x00023] in <0a691c766eee4aee8a7f04da64d1f680>:0

</details>

**Comment by alexeyzimarev** [comment] 2020-05-11 20:12
Platform-specific stuff. Seems like I have to revert the latest change there.

**Comment by alexeyzimarev** [comment] 2020-05-12 20:04
I assume the issue is fixed in the latest version. Please feel free to reopen if it still occurs.

**Closed by alexeyzimarev** 2020-05-12 20:04 UTC

**Comment by genyx** [comment] 2020-05-13 08:10
I came here with the same issue. I am not able to run a RELEASE configuration on Android for my Xamarin project. When the app tries to launch it crashes with the following exception in logcat:

```
The type initializer for 'RestSharp.Extensions.StringEncodingExtensions' threw an exception.
...
NotSupportedException: Encoding 37 data could not be found. Make sure you have correct international codeset assembly installed and enabled
```

I rolled back to the previous RestSharp version until this fix is available via nuget.

**Comment by alexeyzimarev** [comment] 2020-05-13 18:35
@genyx the latest version is on NuGet from the time I closed the issue. The change I made was rolled back. There is no try-catch around the encoding detection though.

**Comment by marra85** [comment] 2020-05-17 09:15
Hello @alexeyzimarev I also have the same issue, and from a rapid check i see that the restsharp package 106.11.4 is not listed on nuget.

by checking the build popup it seems that the pipeline failed to compile and then skipped the nuget push!

<img width="374" alt="CD-pipeline" src="https://user-images.githubusercontent.com/11057667/82140280-0f8cec00-982f-11ea-9d54-6d21f1084c4f.png">

if you could push again the package it would be very appreciated!
thank you!

**Comment by alexeyzimarev** [comment] 2020-05-31 12:18
@marra85 sorry for a delayed response, the package was published a day after your message: https://www.nuget.org/packages/RestSharp/
