### ISSUE TITLE
Can't set a client certificate to my brand spanking new RestClient - WTF ??

### ISSUE THREAD

**Issue by marc-at-nowhow** [restsharp/RestSharp#663] opened 2015-03-26 14:01 UTC
I'm trying to add a client certificate (which I loaded from an embedded resource in my app) to my brand new RestClient - but I keep having a NullReferenceException, since ClientCertificates appears to be 
NULL 

<code>
    private readonly RestClient _restClient;

    /// <summary>
    /// </summary>
    public MyClass() {
        ......
        _restClient = new RestClient();
        _restClient.ClientCertificates.Add(clientCertificate);
    }
</code>

Why is that?? What do I need to do to my RestClient to allow client certificates to be added to that collection without a NullReferenceException???

**Comment by hallem** [comment] 2015-04-02 04:13
It's probably because the collection isn't initialized by default (I haven't confirmed this).  I'd suggest adding a line before your Add statement to initialize it.  I'll take a look in the meantime and see if there is something else going on.

**Comment by hallem** [comment] 2015-04-30 02:19
closing as you need to init the collection before you use it and for age

**Closed by hallem** 2015-04-30 02:19 UTC
