### ISSUE TITLE
Method.POST is not working with Web API

### ISSUE THREAD

**Issue by garora** [restsharp/RestSharp#622] opened 2014-12-26 14:23 UTC
The same issue has been logged on SO. Unfortunately, I did not get any response. Sorry, guys to ask this here:

I have tried all possible scenarios as per RestSharp.org documentation but no luck!
I have ASP.Net Web API here is the POST resource

```csharp
[Route("/api/saveperson/{name}/{fathername}")]    
public void Post([FromBody]CustomObject customObject, string name, string fatherName)
{
      //customObject is null
}
```

RestSharp request:

```csharp
public void SomeAPIRequest()
{
 var baseUrl = "someurl from config";
var client = new RestClient(baseUrl);
var request = new RestRequest("/api/saverperson/{name}/{fathername}",Method.POST);
request.RequestFormat = DataFormat.Json;
request.AddBody(myObject);  //This object is perfectly serialized in json
request.AddParameter("name","Gaurav",ParameterType.UrlSegment);
request.AddParameter("fathername","Lt. Sh. Ramkrishan",ParameterType.UrlSegment);

var response= client.Execute(request);

}
```

With above code Parameter posted in Body is always null.

When, I made following call, Parameter posted in Body is having value but others are null

```csharp
public void SomeAPIRequest()
{
 var baseUrl = "someurl from config";
var client = new RestClient(baseUrl);
var request = new RestRequest("/api/saverperson/{name}/{fathername}",Method.POST);
request.RequestFormat = DataFormat.Json;
request.AddBody(myObject);  //This object is perfectly serialized in json
request.AddUrlSegment("name","Gaurav");
request.AddUrlSegment("fathername","Lt. Sh. Ramkrishan");

var response= client.Execute(request);

}
```
Reply will be warmly welcomed!

**Comment by hallem** [comment] 2015-01-06 00:02
First, no worries about posting the problem here.  I monitor this more than anything else so it's the quickest way to get my attention.

I'm not sure I really understand the problem.  Your code looks fine at a glance.  Have you taken a Fiddler capture to make sure that the problem is with RestSharp and not with the endpoint you're posting to?  If you have a Fiddler capture please send it over so I can see what's happening at the request level.

**Comment by garora** [comment] 2015-01-16 10:54
@hallem - thanks for your response.
Yes, it seems the issue is with RestSharp Only. We tried HttpClient which is working fine.
The only is in above is:

```
[Route("/api/saveperson/{name}/{fathername}")]    
public void Post([FromBody]CustomObject customObject, string name, string fatherName)
{
      //customObject is null
}
```
customObject get always null.

**Comment by hallem** [comment] 2015-01-16 23:03
That's interesting.  I've had it work just fine with the web api before.  Do you have any modules in place that would get in the way?  There's not a whole lot I can do since I've got it working for me.  Can you debug a little further and see what is going on inside your system and if it definitely RestSharp let me know what the issue is?

**Comment by garora** [comment] 2015-01-21 14:58
@hallem - Definitely, I would love to do that in coming weekend. Unfortunately we have already removed RestSharp from our project, which seems not good for me. I am a big fan of this :+1: 
Anyways, to convince stockholders I have to find the root-cause of this issue. I would love to make a pull request if I found something interesting

**Comment by hallem** [comment] 2015-01-21 21:46
I'm going to close this in the meantime as it's not reproducible.  Let me know what you find.

**Closed by hallem** 2015-01-21 21:46 UTC
Labels: inquiry

**Comment by garora** [comment] 2015-03-06 11:56
@hallem - I found the issue and resolved it. Actually I need to pass the data format as ```application/json``` after this everything is working fine :100:

**Comment by xiaoyifang** [comment] 2015-11-12 06:32
this is can reproduce.
post request with both addParameter and addBody method invoked will cause such error.
