### ISSUE TITLE
Getting [NotSupportedException: Generic types are not valid.] after upgrading version from  110.2.0 -> 112.0.0

### ISSUE THREAD

**Issue by NeelamYangal** [restsharp/RestSharp#2264] opened 2024-09-18 12:49 UTC
**Issue Description**
I updated the RestSharp version from 110.2.0 to 112.0.0 and encountered the following issue immediately after the site loads:
[NotSupportedException: Generic types are not valid.]

**Expected behavior**
It should work as it did in version 110.2.0. I expect the same behavior even after upgrading.

**Stack trace**
[NotSupportedException: Generic types are not valid.]
   EPiServer.Framework.Initialization.InitializationModule.EngineExecute(HostType hostType, Action`1 engineAction) +1384
   EPiServer.Framework.Initialization.InitializationModule.FrameworkInitialization(HostType hostType) +226
   EPiServer.Global..ctor() +42
   GMGShop.Web.Global..ctor() +37
   ASP.global_asax..ctor() in c:\Windows\Microsoft.NET\Framework64\v4.0.30319\Temporary ASP.NET Files\root\5a2314ef\7a3fa5aa\App_global.asax.0.cs:0

[TargetInvocationException: Exception has been thrown by the target of an invocation.]
   System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck) +0
   System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark) +142
   System.Activator.CreateInstance(Type type, Boolean nonPublic) +107
   System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark) +1473
   System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes) +186
   System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture) +28
   System.Web.HttpRuntime.CreateNonPublicInstance(Type type, Object[] args) +80
   System.Web.HttpApplicationFactory.GetSpecialApplicationInstance(IntPtr appContext, HttpContext context) +182
   System.Web.Hosting.PipelineRuntime.InitializeApplication(IntPtr appContext) +369

[HttpException (0x80004005): Exception has been thrown by the target of an invocation.]
   System.Web.HttpRuntime.FirstRequestInit(HttpContext context) +532
   System.Web.HttpRuntime.EnsureFirstRequestInit(HttpContext context) +111
   System.Web.HttpRuntime.ProcessRequestNotificationPrivate(IIS7WorkerRequest wr, HttpContext context) +719

**Additional Details**
I investigated further to determine which version might have caused the issue and found that the problem exists with RestSharp version 111.3.0. (If it helps to understand the issue)

**Comment by techwithjyo** [comment] 2024-09-24 18:17
Facing same issue in 112.0.0 version.

**Comment by alexeyzimarev** [comment] 2024-09-30 08:05
The issue can be easily resolved by using the latest .NET SDK (8+)

**Comment by zcs-git** [comment] 2024-10-31 17:20
Also getting this error after upgrading restsharp, site is using .net framework 4.8.1.  I can upgrade to Restsharp 111.2.0 but anything later will result in "Generic Types are Invalid".

**Comment by zcs-git** [comment] 2024-11-07 12:32
I get that on runtime on all versions above 111.2.0  using .net framework 4.5.1

**Comment by techwithjyo** [comment] 2024-11-07 12:34
Same here, Getting it in the runtime.

**Comment by zcs-git** [comment] 2024-11-07 15:45
[cid:927fcac1-16bb-4fd1-8010-d5b460536edc]

That would be great if it can be fixed as my client is isn't planning on moving to .net core in the near future. 🙁

________________________________

**Comment by diegotibi** [comment] 2024-12-11 10:43
> Ok, that's not good. I thought you get it at compile time. It's a bummer that the compiler allows it when building for .NET Framework target, but it cannot be executed. It can easily be fixed, it's not required to use generic attributes.

Is there any update on this?

I've lost half a day last week (I didn't saw this issue before...) because I was updating some packages on a project that still relies on .net 4.8 (and cannot be upgraded) and I didn't get that the bug was on Restsharp (I've tried something like downgrading 20 other packages before getting the right one!)

**Comment by alexeyzimarev** [comment] 2024-12-16 21:49
Duplicate of #2245

**Closed by alexeyzimarev** 2024-12-16 21:49 UTC
Labels: bug
