### ISSUE TITLE
AddJsonBody fails because Parameter "name" is empty

### ISSUE THREAD

**Issue by alexbk66** [restsharp/RestSharp#1351] opened 2019-08-14 12:09 UTC
## Steps to Reproduce the Problem

  1. Call AddJsonBody()

## Details:

`AddJsonBody(object obj)` calls 
`AddParameter(new JsonParameter("", obj));` which calls 
`JsonParameter()` with empty name,
`Parameter() `ctor checks 
`Ensure.NotEmpty(name, nameof(name));`

## StackTrace
RestSharp.dll!RestSharp.Parameter.Parameter(string name, object value, RestSharp.ParameterType type) Line 30
RestSharp.dll!RestSharp.RestRequest.AddJsonBody(object obj) Line 336
 	HSPI_AKSonoff.exe!HSPI_AKSonoff.DeviceSonoffRoot.Execute<HSPI_AKSonoff.DeviceSonoffRoot.Response>(string command, object json, int timeout, RestSharp.Method method) Line 414

**Comment by kd5ziy** [comment] 2019-08-29 20:23
Has this been fixed?

**Comment by alexbk66** [comment] 2019-08-30 00:36
I downloaded the source and fixed it for myself.  But nobody else replied.

**Comment by alexeyzimarev** [comment] 2019-08-30 06:36
@alexbk66 if you fixed it, maybe you could've spent five more minutes and submitted a PR so this issue can be closed?

**Comment by alexbk66** [comment] 2019-08-30 11:57
@alexeyzimarev - I "fixed" it by passing an arbitrary name instead of empty string.  It seems to work, but  I'm not sure if it's a correct fix.  Since there's no comments - I have no idea what the string 'name' is supposed to be and what it's used for.

`AddParameter(new JsonParameter("JsonBody", obj));`

**Comment by kd5ziy** [comment] 2019-08-30 16:04
So, I realized yesterday that this issue is the same as Issue # 1300.  I ended up fixing this on my side by checking if the parameter is a body parameter.  If so then skip the empty name check.  I can put in a PR today.

**Comment by alexbk66** [comment] 2019-08-31 13:29
Well, at least one of the issues should be closed as duplicate then.

**Comment by alexeyzimarev** [comment] 2019-10-12 15:17
Duplicate of #1300

**Closed by alexeyzimarev** 2019-10-12 15:17 UTC
