### ISSUE TITLE
Allow setting CachingPolicy for the request

### ISSUE THREAD

**Issue by galmeida** [restsharp/RestSharp#401] opened 2013-08-21 09:57 UTC
That's it. It would be nice to have a way to set a CachingPolicy for request.

**Comment by dgreenbean** [comment] 2015-06-24 15:47
I just created a pull request for a more limited version of the original change proposed. This does not change the default functionality, but it does add the ability to set the cache policy on a client.

This is important, as the only workaround currently is to set the cache policy globally for a process. In general, it is better to limit the scope of the policy to a specific client wrapper, i.e. only specific requests.

**Comment by elmerillion** [comment] 2015-10-14 21:30
This was merged but doesn't appear to be active due to the "#if FRAMEWORK" checks. Is there a compiler directive missing?

**Comment by dgreenbean** [comment] 2015-10-22 15:44
@elmerillion I see the change when I pull version 105.2.3 from NuGet.  This change will, of course, only work for builds with the FRAMEWORK variable defined in the project file, e.g.: https://github.com/restsharp/RestSharp/blob/master/RestSharp/RestSharp.Net35.csproj#L44

This means that if you need it for Silverlight, Windows Phone, iOS, etc., support would need to be added in a separate pull request.  I was very conservative with my pull request to limit the impact of the change.

**Comment by elmerillion** [comment] 2015-10-23 21:38
@dgreenbean thanks, I think I had a pre-merge version loaded for some reason and couldn't find the property. My mistake!

**Comment by alexeyzimarev** [comment] 2017-11-18 14:12
I assume since the PR was accepted, the issue is now resolved.

**Closed by alexeyzimarev** 2017-11-18 14:12 UTC
