### ISSUE TITLE
RestClient.cs p2.Name - null exception thrown due to null request.Parameters Name property

### ISSUE THREAD

**Issue by j4m355** [restsharp/RestSharp#904] opened 2016-12-07 10:32 UTC
Hi,

I am coming against an issue that seems to originate from within RestClient.cs when the code is attempting to add an Accept header based on the registered deserializers.

These are observations, I am not sure if it is intentional, or what the best fix is. I have been using this library quite successfully for a number of years now and have just recently encountered this issue.  (Potentially related to #881 )

```
 if (request.Parameters.All(p2 => p2.Name.ToLowerInvariant() != "accept"))
            {
                string accepts = string.Join(", ", this.AcceptTypes.ToArray());
                request.AddParameter("Accept", accepts, ParameterType.HttpHeader);
            }
```

In the context within which I am using the library I can see quite clearly that my request body object is perhaps the problem as this property within the Parameters List has a null name value:

**Request Body:**
![screen shot 2016-12-07 at 10 21 30](https://cloud.githubusercontent.com/assets/1112047/20963868/2334a3e4-bc67-11e6-9a1b-9064694f7cf4.png)

**Whole Parameters List:**
![screen shot 2016-12-07 at 10 29 49](https://cloud.githubusercontent.com/assets/1112047/20964195/69425038-bc68-11e6-8428-7173de0ba49e.png)

I'm unsure as to why this has suddenly started to become a problem - because this part of RestClient.cs has not changed recently. Although perhaps it is a problem that was introduced on up the chain (and perhaps indicative of the other issues regarding null properties).

Open to suggestions for creating a fix for this.  In the short term and for my own use i've put a null check in here when p2.Name is evaluated. I've a feeling however that this is not the best fix.

Appreciate any feedback / comments. Thanks.

**Comment by alexeyzimarev** [comment] 2017-10-25 18:14
Duplicate of #890 and/or #881

**Closed by alexeyzimarev** 2017-10-25 18:14 UTC
