### ISSUE TITLE
Get statuscode in responsewriter

### ISSUE THREAD

**Issue by PaulVrugt** [restsharp/RestSharp#1212] opened 2018-10-29 14:42 UTC
## Expected Behavior
When i execute a restsharp command to download a file, and use a responsewriter to stream the response, I would like to know what the status code of the request is. 

The problem is, that the status code is now set after the responsewriter has finished. This causes the actual response message containing the error is written to the output stream, instead of the file data I'm expecting.

## Steps to Reproduce the Problem

  1. Call an api returning a file, use a responsewriter to read the output stream
  2. generate an error in the api, causing it to return (for instance) a 400
  3. there is no way to get the status code without first downloading the response to a stream.

**Comment by alexeyzimarev** [comment] 2018-10-29 19:48
It is being addressed in #1208

**Comment by alexeyzimarev** [comment] 2018-10-29 19:49
Duplicate of #1207

**Closed by alexeyzimarev** 2018-10-29 19:49 UTC

**Comment by apierini** [comment] 2025-03-26 12:05
I think the problem is here again because AdvancedResponseWriter changed in version 107+. Is there another solution to get the status code before the responsewriter has finished?

**Comment by apierini** [comment] 2025-03-28 15:21
> https://restsharp.dev/docs/advanced/interceptors

Thanks, it works. Interceptors are powerful, but in my opinion for this particular use case (very common indeed), the old AdvancedResponseWriter was better.

**Comment by alexeyzimarev** [comment] 2025-03-31 09:51
Yeah but there's another issue for handling download errors. It should be solved differently.
