### ISSUE TITLE
 System.Net.WebException: The server committed a protocol violation.

### ISSUE THREAD

**Issue by phillipzada** [restsharp/RestSharp#830] opened 2016-04-09 22:44 UTC
When making multiple calls (after each other) the first call works correctly then the send throws and error.   System.Net.WebException: The server committed a protocol violation. Section=ResponseStatusLine

**Comment by phillsta** [comment] 2016-04-10 00:33
Found a temporary workaround, where if i catch the error and resubmit a new request then it works. 
I'm running it on a .Net Console App with only net451 (remove net5)

```
dnx --version
Microsoft .NET Execution environment
 Version:      1.0.0-rc1-16231
 Type:         Clr
 Architecture: x86
 OS Name:      Windows
 OS Version:   10.0
 Runtime Id:   win10-x86
```

**Comment by hallem** [comment] 2016-04-26 19:24
I'm going to need more information on what's happening.  I've been able to make successful back to back calls with no trouble.

**Comment by monty241** [comment] 2016-10-08 21:34
Same problem on gitlab, after several pages of 20 records this exception is thrown. Strange thing is that the URL is like:

https://gitlab.com/api/v3/users?page=32&per_page=20

But it works in the browser when opened isolated.

Running .NET 4.5.2 with a console application, web application and windows application. Reproducible, just the number of pages fetched before the error appears differs. Tried some times, other numbers 32, 81, 108. Some pages might have been cached on a previous run, but the number of additional pages also differs: 32, 49, 27.

Seems to occur only on users, tested it on [https://online-sql-editor.com/gitlab/com/stable/Sql](https://online-sql-editor.com/gitlab/com/stable/Sql) using the following statement:

`select * from users`

`select * from projects` -> works
`select * from commits(projectid)` -> works

**Comment by PhillipZada** [comment] 2016-10-09 23:14
I think this error has the do with the backend webclient using  keep connection active header. Is there a way we can flag this to false?

**Comment by PhillipZada** [comment] 2016-10-24 00:09
Hi @hallem ,

Just wanted to see if there has been any progress on this one. Below is the Exception i'm getting. It looks like its happening randomly and has to do with the underlying webclient. Let me know what else you need to diagnose. Most of the material around this that I've read so far points to the **Keep-Alive** header. Is there a way you make it configurable from RestSharp Client? 

There is also reference to:
 * 204 returning data (though I've ruled this out in my case)
 * setting the useUnsafeHeaderParsing property.

See: 
http://stackoverflow.com/questions/23747973/the-server-committed-a-protocol-violation-section-responsestatusline-in-c-sharp
http://stackoverflow.com/questions/2482715/the-server-committed-a-protocol-violation-section-responsestatusline-error

Can you also confirm if you are using the Webclient within a "using" statement or have it statically referenced?

### Exception
```
"ClassName": "System.Net.WebException",
            "Message": "The server committed a protocol violation. Section=ResponseStatusLine",
            "Data": null,
            "InnerException": null,
            "HelpURL": null,
            "StackTraceString": "   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at RestSharp.Http.GetRawResponseAsync(IAsyncResult result, Action`1 callback)\r\n   at RestSharp.Http.ResponseCallback(IAsyncResult result, Action`1 callback)",
            "RemoteStackTraceString": null,
            "RemoteStackIndex": 0,
            "ExceptionMethod": "8\nEndGetResponse\nSystem, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089\nSystem.Net.HttpWebRequest\nSystem.Net.WebResponse EndGetResponse(System.IAsyncResult)",
            "HResult": -2146233079,
            "Source": "System",
            "WatsonBuckets": null
```

**Comment by huhobocot** [comment] 2016-12-01 14:05
I have a service that synchronizes my accounts with an external service. Starting synchronization triggered by a timer. And it works perfect, bu after some times service began sending bug reports. After restart, the service work again.

I attach bug report:
System.ApplicationException: Error retrieving response from Capsule CRM API. Check inner details for more info. ---> System.Net.WebException: The server committed a protocol violation. Section=ResponseStatusLine
   at System.Net.HttpWebRequest.GetResponse()
   at RestSharp.Http.GetRawResponse(HttpWebRequest request)
   at RestSharp.Http.GetResponse(HttpWebRequest request)
   --- End of inner exception stack trace ---
   at IMath.ExternalServices.CapsuleCrm.CapsuleApi.ErrorHandling[T](IRestResponse`1 response) in d:\BuildAgent\work\3f9675c8866b5706\WebArchitecture\IMath.ExternalServices\CapsuleCrm\CapsuleApi.cs:line 157
   at IMath.ExternalServices.CapsuleCrm.CapsuleApi.Execute[T](RestRequest request) in d:\BuildAgent\work\3f9675c8866b5706\WebArchitecture\IMath.ExternalServices\CapsuleCrm\CapsuleApi.cs:line 45
   at IMath.ExternalServices.CapsuleCrm.Services.PersonService.GetPerson(String personId) in d:\BuildAgent\work\3f9675c8866b5706\WebArchitecture\IMath.ExternalServices\CapsuleCrm\Services\PersonService.cs:line 64

**Comment by huhobocot** [comment] 2016-12-01 14:11
Is there a way set KeepAlive to false?

**Comment by thiagoalmedeiros** [comment] 2017-03-28 17:43
Hello everyone, has anyone had any progress with this error? I'm having this error while making multiple soap requests.

**Comment by thiagoalmedeiros** [comment] 2017-03-28 23:52
`ServicePointManager.Expect100Continue = false;
ServicePointManager.MaxServicePointIdleTime = 0`


I solved my problem by putting these two properties in the **global.asax**

**Comment by Sire** [comment] 2017-04-03 14:25
I tried to set KeepAlive to false without luck (the latest version has this feature). Had success with the work around from @thiagoalmedeiros

**Comment by olguinitron** [comment] 2018-04-20 21:01
Same here, had the same problem and I resolved it with the @thiagoalmedeiros solution

**Comment by alexeyzimarev** [comment] 2019-01-20 22:57
It is a .NET thing, not RestSharp. Since the solution is confirmed working, I am closing the issue.

**Closed by alexeyzimarev** 2019-01-20 22:57 UTC
Labels: inquiry

**Comment by bakicaglar** [comment] 2022-05-19 13:42
I was getting the same error and was able to reproduce by making the following REST Calls right one after another:

1. DELETE /resource/{id=42}
2. GET /resource/{id=7}

I have set the client KeepAlive setting of the Client to false and since then, the error did not return:

`_client.ConfigureWebRequest(request => request.KeepAlive = false);`
