### ISSUE TITLE
Unable to parse JSON response (yesterday I was)

### ISSUE THREAD

**Issue by SteMMo33** [restsharp/RestSharp#2217] opened 2024-05-28 14:16 UTC
Hi there,
I'm developing a C# app by vs2022.
I installed RestSharp by NuGet --> version 111.1.0
Some JSON replies that until yesterday was parsed, now they are not. (???)

The request is (contains two requests ..):
```
			var client = InitRest();
			var request = new RestRequest("GetTornei.php", Method.Get);

			List<Torneo> list = new List<Torneo>();
			try
			{
				var list2 = client.GetJson<TorneiQuery>("GetTornei.php");

				var response = client.ExecuteGet<TorneiQuery>(request);
				Debug.WriteLine(response.Content);
				Debug.WriteLine(response.StatusCode);
				if (response.StatusCode == HttpStatusCode.OK)
				{
					//list = response.Data.list;
				}

				statusCode = response.StatusCode;
```

The class is:

```
namespace TorneoSB
{
	public class Torneo
	{
		// I membri devono essere 'proprietà' per consentire il parsing JSON

		public string id { get; set; }		// Da query arriva una stringa
		public string nome { get; set; }
	}

}
```

The response is the following (copy and pasted from the debugger:
```
" {\"list\":[{\"id\":\"2020\",\"nome\":\"Prova torneo - Trofeo\"},{\"id\":\"2023\",\"nome\":\"36\\u00b0 Torneo - Trofeo Ermes Fontana\"}],\"ret\":\"ok\"}"
```
The response is without any exception, I set the client members as 
```
			ThrowOnDeserializationError = true,
			FailOnDeserializationError = true,
```
and Data is null without errors.

![Screenshot 2024-05-28 160354](https://github.com/restsharp/RestSharp/assets/8493374/20ad55e0-d191-4c36-9b4d-7579dc7746aa)

If I visualize the Content member with the JSON viewer I correctly see:
![Screenshot 2024-05-28 160456](https://github.com/restsharp/RestSharp/assets/8493374/6c6e22e7-0e31-4ae0-9699-bd4b9c7614bd)

Just one note: the contentType is text/html --> is it misunderstood ??

Thanks!

**Comment by SteMMo33** [comment] 2024-05-28 18:11
I recovered my last version of the project: it had restsharp 110.2.0 and it was Ok.
Hope it help .

**Comment by alexeyzimarev** [comment] 2024-05-30 11:08
What's the code for `TorneiQuery`?

Also, `text/html` is apparently wrong as the response is JSON and it should have an appropriate content type, but it should work regardless.

**Comment by alexeyzimarev** [comment] 2024-05-30 11:09
This would work:

```csharp
var response = client.ExecuteGet<Torneo[]>(request);
```

**Comment by SteMMo33** [comment] 2024-05-30 14:18
Sorry I missed the class(es):

```
		public class TorneoQuery
		{
			public string id { get; set; }
			public string nome { get; set; }
		}

		class TorneiQuery
		{
			public string ret { get; set; }
			public List<TorneoQuery> list { get; set; }
		}
```
I returned to 110.2.0 and I have no problems.

**Comment by alexeyzimarev** [comment] 2024-06-03 11:55
When you say this
> Some JSON replies that until yesterday was parsed, now they are not. (???)
what does it mean?

**Comment by SteMMo33** [comment] 2024-06-03 13:35
Sorry .. simply that in that day I forgot that I had a library update to 111.1.0.
Then I restored restsharp  version 110.2.0 and since that day the parses were Ok.

**Comment by alexeyzimarev** [comment] 2024-06-03 14:04
That I understand, but I still don't know what you've got with 111.0

**Comment by SteMMo33** [comment] 2024-06-04 12:00
Version 111.1.0 does not parse the json string that 110.2.0 does.

**Comment by alexeyzimarev** [comment] 2024-06-20 11:05
Sorry, I don't know how to help you. If you can create a reproduction repo, it can be fixed. Otherwise, it's too hard as you have some JSON and some classes on your side, which I can't see. RestSharp has a bunch of tests for JSON calls and all of them pass on the latest version, so I am not sure what is wrong there.

**Comment by SteMMo33** [comment] 2024-06-24 10:53
Today I updated the verion to the lastone at this moment: 111.3.0.
Again the parse is failed but the StatusCode=OK and no any Exceptions.
The Content is:

     {"list":[{"id":"2020","nome":"Prova torneo - Trofeo"},{"id":"2023","nome":"36\u00b0 Torneo - Trofeo Ermes Fontana"}],"ret":"ok","user":"username","pass":"password","digest":null}

The error is that response.Data is null.
The code is:

    var response = client.ExecuteGet<TorneiQuery>(request);

and the class(es) is:

		public class TorneoQuery
		{
			public string id { get; set; }
			public string nome { get; set; }
		}

		class TorneiQuery
		{
			public string ret { get; set; }
			public List<TorneoQuery> list { get; set; }
		}

Again, with version 110.2.0 everyting is ok.
Hope this help .. thanks

**Comment by alexeyzimarev** [comment] 2024-06-24 12:04
Please spend 10 minutes of your time and compose a repro available for public in a GitHub repository.

**Comment by alexeyzimarev** [comment] 2024-09-11 19:12
Closing due to lack of communication.

**Closed** 2024-09-11 19:13 UTC
Labels: awaiting-info

**Comment by SteMMo33** [comment] 2024-11-13 11:07
Hello,
this is my sample to check the problem: now is against v.112.1.0
This is a small request with JSON reply that is not parsed. v.110.2.0 was able to parse it.
Github: https://github.com/SteMMo33/TestVari

**Comment by SteMMo33** [comment] 2024-11-13 14:07
There is no authentication.
If I insert the URL https://www.salabaganzabc.com/Torneo/1.1/GetTornei.php in a browser I receive the response.

**Comment by alexeyzimarev** [comment] 2024-11-13 15:05
Yeah, you're right, I was trying the base URL.

**Comment by SteMMo33** [comment] 2024-12-13 12:53
Finally I solved forcing the server reply with
`header('Content-Type: application/json');`
directive.
