### ISSUE TITLE
The value cannot be null or empty. (Parameter 'mediaType')

### ISSUE THREAD

**Issue by guyulmaz** [restsharp/RestSharp#1999] opened 2023-01-15 12:44 UTC
**DO NOT USE ISSUES FOR QUESTIONS**

**Describe the bug**
Hint: use a tool like https://requestbin.com to compare working and non-working requests.

.net 7 is giving this error. .net 6 dont have this problem.

var client = new RestClient();
var request = new RestRequest("...api", Method.Post);
request.AlwaysMultipartFormData = true;
request.AddParameter("x", "y");
request.AddParameter("xx", "yy");...
return await client.ExecuteAsync(request);

System.AggregateException: One or more errors occurred. (The value cannot be null or empty. (Parameter 'mediaType'))  ---> System.ArgumentException: The value cannot be null or empty. (Parameter 'mediaType')
   at System.Net.Http.Headers.MediaTypeHeaderValue.CheckMediaTypeFormat(String mediaType, String parameterName)
   at System.Net.Http.StringContent..ctor(String content, Encoding encoding, String mediaType)
   at RestSharp.RequestContent.AddPostParameters(ParametersCollection postParameters)
   at RestSharp.RequestContent.BuildContent()
   at RestSharp.RestClient.ExecuteInternal(RestRequest request, CancellationToken cancellationToken)
   at RestSharp.RestClient.ExecuteAsync(RestRequest request, CancellationToken cancellationToken)

**To Reproduce**
Steps to reproduce the behavior, preferably using a code snippet. 
Post the non-working request here as well if you made it work using Postman, Swagger, or any other client.

**Expected behavior**
Post the working request here as well if you made it work using Postman, Swagger, or any other client.
You can use https://requestbin.com/r to create a public request bin and share the link in the issue.

**Stack trace**
Copy the full stack trace here if you get an exception.

**Desktop (please complete the following information):**
 - OS: [e.g. macOS]
 - .NET version [e.g. .NET 5]
 - Version [e.g. 107.0.4]
 .net 7.0.2
windows 10
restsharp 108.0.3

**Additional context**

**Comment by alexeyzimarev** [comment] 2023-01-15 14:28
Duplicate of #1969

**Closed by alexeyzimarev** 2023-01-15 14:28 UTC
Labels: bug
