### ISSUE TITLE
Post with file parameter order

### ISSUE THREAD

**Issue by kyugoa** [restsharp/RestSharp#2115] opened 2023-07-14 03:03 UTC
**DO NOT USE ISSUES FOR QUESTIONS**

**Describe the bug**
when posting to an endpoint with File attachment, if there are other input parameters in the body, the File parameter is always render first regardless of the order the parameter is added. 

**To Reproduce**
call an api endpoint with file attachment and additional parameter like fileName and fileType. 

`    using var fileServiceClient = GetFileServiceClient();
     var request = new RestRequest("file/v1/files", Method.Post);

      //added these parameters first
      request.AddJsonBody(new FileUploadRequestModel { Type = "tps-volume-titles", FileName = fileName });

      //then the file parameter
      request.AddFile("file", fileContent, fileName, "text/csv");
      request.AlwaysMultipartFormData = true;

      var response = await fileServiceClient.PostAsync(request).ConfigureAwait(false);

      if (!response.IsSuccessStatusCode)
      {
        _logger.LogError($"Failed to upload file {fileName}");
      }
`

**Expected behavior**
Expected the http request to be:

POST https://somedomain.com/file/v1/files HTTP/1.1
Host: file-service.adsp-uat.alberta.ca
Authorization: Bearer eyxxx
Accept: application/json, text/json, text/x-json, text/javascript, application/xml, text/xml
User-Agent: RestSharp/110.2.0.0
Accept-Encoding: gzip, deflate, br
Content-Type: multipart/form-data; boundary="0a1f4db8-6981-4592-aff5-7b12b4e00197"
Content-Length: 115113

--0a1f4db8-6981-4592-aff5-7b12b4e00197
Content-Type: text/plain; charset=utf-8
Content-Disposition: form-data; name=type

tps-volume-titles
--0a1f4db8-6981-4592-aff5-7b12b4e00197
Content-Type: text/plain; charset=utf-8
Content-Disposition: form-data; name=filename

1680672668.csv
--0a1f4db8-6981-4592-aff5-7b12b4e00197
Content-Type: text/csv
Content-Disposition: form-data; name="file"; filename="1680672668.csv"

"xxx","2023-07-13 09:28:48",,ON00001,,"242006882001","S","*",,"2023-07-11","Subdivision Plan",,,"N",,"T","Fee Simple","242 006 882 +2",,,"2023-07-11"

--0a1f4db8-6981-4592-aff5-7b12b4e00197--

**Actual rendered http request**

POST https://somedomain.com/file/v1/files HTTP/1.1
Host: file-service.adsp-uat.alberta.ca
Authorization: Bearer eyxxx
Accept: application/json, text/json, text/x-json, text/javascript, application/xml, text/xml
User-Agent: RestSharp/110.2.0.0
Accept-Encoding: gzip, deflate, br
Content-Type: multipart/form-data; boundary="0a1f4db8-6981-4592-aff5-7b12b4e00197"
Content-Length: 115113

--0a1f4db8-6981-4592-aff5-7b12b4e00197
Content-Type: text/csv
Content-Disposition: form-data; name="file"; filename="1680672668.csv"

"xxx","2023-07-13 09:28:48",,ON00001,,"242006882001","S","*",,"2023-07-11","Subdivision Plan",,,"N",,"T","Fee Simple","242 006 882 +2",,,"2023-07-11"

--0a1f4db8-6981-4592-aff5-7b12b4e00197
Content-Type: text/plain; charset=utf-8
Content-Disposition: form-data; name=type

tps-volume-titles
--0a1f4db8-6981-4592-aff5-7b12b4e00197
Content-Type: text/plain; charset=utf-8
Content-Disposition: form-data; name=filename

1680672668.csv
--0a1f4db8-6981-4592-aff5-7b12b4e00197--

**Stack trace**

**Desktop (please complete the following information):**
 - OS: windows
 - .NET version 6
 - Version  110.2.0

**Additional context**

**Comment by b166er** [comment] 2023-07-14 17:20
I have the same problem! Here is my ugly code to set the order manually. It would be so great if the output of the parameters were in the same order as the input! and an additional feature request: the possibility to set the "Content-Type multipart/mixin" instead of the default type "multipart/form-data" for files.

```c#

using System.Text;
using System.Linq;

class Program
{
    static void Main(string[] args)
    {
        // Create RestClient
        RestClient client = new RestClient("https://api-server");
        
        // Create RestRequest
        RestRequest request = new RestRequest(Method.POST);
        
        string boundary = "MySpecialBounderyIdentifierTest123";
        string filename = "mytest.xlsx";
        
        byte[] start = Encoding.UTF8.GetBytes($"--{boundary}{Environment.NewLine}");
        byte[] separator = Encoding.UTF8.GetBytes($"{Environment.NewLine}{boundary}--{Environment.NewLine}");
        byte[] end = Encoding.UTF8.GetBytes($"{Environment.NewLine}--{boundary}--{Environment.NewLine}");
        
        string json = @"{
            ""meta"": [{
                    ""title"": ""My Homework"",
                    ""author"": 
                    {
                        ""name"": ""Tessa"",
                        ""adress"": null
                    }, 
                    ""created"": 1550743894373
                }]
        }";
        // Content-Disposition is optional and not necessary for me/the api-server
        byte[] jsonMeta = Encoding.UTF8.GetBytes($"Content-Type: application/json{Environment.NewLine}{Environment.NewLine}{json}");
        byte[] fileMeta = Encoding.UTF8.GetBytes($"Content-Type: application/pdf{Environment.NewLine}Content-Disposition: form-data; name=\"file\"; filename=\"{filename}\"{Environment.NewLine}{Environment.NewLine}");
        
        // use Linqs byte-concatenation
        IEnumerable<byte> requestBytes;
        
        // Combine first json data, then file content! the order is very important.
        requestBytes = start // start with boundary-start-sequence
            .Concat(jsonMeta) // important: json Data MUST be in the first position, before binary file payload
            .Concat(separator) // add boundary separator
            .Concat(fileMeta) // file data need as second parameter, after json data!
            .Concat(File.ReadAllBytes(filename)) // add file binary payload data as bytes
            .Concat(end) // add boundary-endsequence
        ;
        
        // multipart/mixin is very important, multipart/form-data does not work with this particular api server!
        request.AddParameter($"multipart/mixin; boundary={boundary}", requestBytes.toArray(), ParameterType.RequestBody);
        
        // Execute the request
        IRestResponse response = client.Execute(request);
        
        // Handle the response
        if (response.IsSuccessful)
        {
            Console.WriteLine("File uploaded successfully!");
        }
        else
        {
            Console.WriteLine("File upload failed. Error: " + response.ErrorMessage);
        }       
    }
}

```

**Comment by koo9** [comment] 2023-07-14 19:40
just render the paramter by the order added would be sufficient. I believe you can set the file content type in the .AddFile() method but the overall content-type is still multipart/form-data

**Comment by alexeyzimarev** [comment] 2023-07-15 11:38
Body parameters are added to the request message in the same order as they are added to `RestRequest`. But, files are added separately, as well as POST parameters when the content is a multipart form.

**Comment by alexeyzimarev** [comment] 2023-07-15 11:39
Duplicate of #2098

**Closed by alexeyzimarev** 2023-07-15 11:39 UTC
Labels: feature-request
