### ISSUE TITLE
Responses gets mixed when used with parallel.foreach

### ISSUE THREAD

**Issue by montumodi** [restsharp/RestSharp#770] opened 2015-10-23 04:32 UTC
I am not sure if rest sharp is thread safe or not but for some reason when i am running 10k requests in parallel, it is mixing the responses. 

e.g : 1 response is getting attached to multiple requests.

Any pointer?

**Comment by hallem** [comment] 2015-11-03 18:47
i'm not sure honestly.  it depends on how you're calling things too.  i don't use the parallel foreach much so it's never come up for me.

**Comment by spamguy** [comment] 2015-11-17 21:02
Same. I usually spawn one client per thread to work around this.

**Comment by alexeyzimarev** [comment] 2017-10-25 18:46
Duplicate of #951

**Closed by alexeyzimarev** 2017-10-25 18:46 UTC
Labels: inquiry
