### ISSUE TITLE
RestSharp does not support colons in Uri path

### ISSUE THREAD

**Issue by ashley-kelham** [restsharp/RestSharp#1500] opened 2020-09-17 02:40 UTC
## Expected Behavior
If I provide a valid baseUrl to the RestClient e.g. https://myapi.com and then provide a request path with a colon e.g. /myresource:sync I would expect the request to be made to the API when I call client.Execute.

## Actual Behavior
When the request is made you get an error "the uri prefix is not recognized". 

```
 RestClient client = new RestClient("https://myapi.com");
 RestRequest request = new RestRequest(Method(HttpMethod.Get))
         {
                Resource = "/myresource:sync"
         };
var response = client .Execute(request); 
//response.ErrorMesage contains error "the uri prefix is not recognized"

```
## Specifications

RFC1738 says that : (amongst other characters) may be reserved for special meaning within a scheme. However the http scheme does not reserve it in the path part

Within the path and searchpart components, "/", ";", "?" are reserved. (Not :.)

hsegment       = *[ uchar | ";" | ":" | "@" | "&" | "=" ]

</details>

**Comment by nesc58** [comment] 2020-09-17 14:04
This is not a problem of RestSharp at all. It is a problem of Microsofts URL implementation.
I have found a stackoverflow post: https://stackoverflow.com/a/6704287

_Combine_ the two parts: `https://myapi.com` and `resource:sync` will result in `resource:sync`: https://github.com/restsharp/RestSharp/blob/dev/src/RestSharp/RestClient.cs#L326


@alexeyzimarev what do you think about the `CombineUri` method described in the stackoverflow post?

**Comment by alexeyzimarev** [comment] 2020-09-17 18:13
I think we can pull the SO answer code and use it instead. Indeed, the `Uri` concatenation has been a troublemaker for a while.

**Comment by alexeyzimarev** [comment] 2020-09-17 18:14
I don't feel it's even RestSharp concern to ensure that the URI is valid... Preliminary validation for the basic properties like schema and separators would be enough.

**Comment by cloudhunter89** [comment] 2020-12-18 12:56
This looks like it is a duplicate of #1473

**Comment by alexeyzimarev** [comment] 2021-03-23 07:51
Will keep this one open as #1473 was closed.

**Closed** 2021-06-25 14:26 UTC
Labels: good first issue, help wanted, wontfix
