### ISSUE TITLE
Trouble serializing/deserializing Dictionaries

### ISSUE THREAD

**Issue by JackHWarnerJrPE** [restsharp/RestSharp#1155] opened 2018-08-17 20:37 UTC
## Expected Behavior
I create a class that contains a Dictionary. I then use RestSharp to serialize to JSON, and then expect to be able to deserialize it back.

## Actual Behavior
I create a class that contains a Dictionary. I then use RestSharp to serialize to JSON, and then get an error trying to deserialize it back(see stack trace below).

## Steps to Reproduce the Problem

Create a simple program that has one class (Big) that contains a dictionary of another class (Small).
Serialize the class to JSON. Program code below yields this:

{"bigProp1":9,"smalls":[{"Key":"a","Value":{"smallProp":40}},{"Key":"b","Value":{"smallProp":50}}]}

Deserialize back to the same types of objects (get error). Here is a simple version of the C# code in a console program:

using System;
using System.Collections.Generic;

namespace RestSharpTest1
{
	public class Small
	{
		public Small() { smallProp = 0; }
		public Small(int i1) { smallProp = i1; }
		public int smallProp { get; set; }
	}

	public class Big
	{
		public Big()
		{
			bigProp1 = 0;
			smalls = new Dictionary<string, Small>();
		}
		public int bigProp1 { get; set; }
		public Dictionary<string, Small> smalls { get; set; }
	}

	class Program
	{
		static void Main(string[] args)
		{
			try
			{
				Small s1 = new Small(40);
				Small s2 = new Small(50);
				Big b = new Big();
				b.bigProp1 = 9;
				b.smalls.Add("a", s1);
				b.smalls.Add("b", s2);

				RestSharp.Serializers.JsonSerializer jsonS = new RestSharp.Serializers.JsonSerializer();
				string jsonText = jsonS.Serialize(b);
				System.IO.File.WriteAllText(@"d:\json.txt", jsonText);

				RestSharp.RestResponse response = new RestSharp.RestResponse();
				response.Content = jsonText;
				RestSharp.Deserializers.JsonDeserializer deserial = new RestSharp.Deserializers.JsonDeserializer();
				Big b2 = deserial.Deserialize<Big>(response);
				System.Console.WriteLine("done");
			}
			catch(Exception e)
			{
				System.Console.WriteLine(e.ToString());
			}
		}
	}
}

## Specifications

  - Version: 106.3.1.0
  - Platform: .net
  - Subsystem: Windows 7

## StackTrace
<details>
System.InvalidCastException: Unable to cast object of type 'SimpleJson.JsonArray' to type 'System.Collections.Generic.IDictionary`2[System.String,System.Object]'.
   at RestSharp.Deserializers.JsonDeserializer.BuildDictionary(Type type, Object parent)
   at RestSharp.Deserializers.JsonDeserializer.ConvertValue(TypeInfo typeInfo, Object value)
   at RestSharp.Deserializers.JsonDeserializer.Map(Object target, IDictionary`2 data)
   at RestSharp.Deserializers.JsonDeserializer.CreateAndMap(Type type, Object element)
   at RestSharp.Deserializers.JsonDeserializer.ConvertValue(TypeInfo typeInfo, Object value)
   at RestSharp.Deserializers.JsonDeserializer.Deserialize[T](IRestResponse response)
   at RestSharpTest1.Program.Main(String[] args) in D:\Users\Jack.Warner\RestSharpTest1\Program.cs:line 45
</details>

**Comment by alexeyzimarev** [comment] 2018-08-17 21:05
Duplicate of #1105?

**Comment by JackHWarnerJrPE** [comment] 2018-08-18 01:50
It does indeed put the [ ] around the dictionary, if that is incorrect. I removed the [ ], but I get an invalid JSON error when I try to deserialize:
System.Runtime.Serialization.SerializationException: Invalid JSON string
   at SimpleJson.SimpleJson.DeserializeObject(String json)
   at RestSharp.Deserializers.JsonDeserializer.FindRoot(String content)
   at RestSharp.Deserializers.JsonDeserializer.Deserialize[T](IRestResponse response)
   at RestSharpTest1.Program.Main(String[] args) in D:\Users\Jack.Warner\RestSharpTest1\Program.cs:line 45

**Comment by alexeyzimarev** [comment] 2018-08-18 08:15
To be honest, I counted the number of JSON-related issues and now lean more and more towards bringing Newtonsoft.Json back as a dependency and making Json.Net serializer as the default one. 

I am wondering what people think about it?

**Comment by JackHWarnerJrPE** [comment] 2018-08-20 16:05
I am fairly new to all this, but I will say that switching to Newtonsoft Json seemed to take care of this issue.

**Comment by clegoz** [comment] 2018-09-24 22:42
I was looking on this issue and I found that [SimpleJson](https://github.com/facebook-csharp-sdk/simple-json) serializes the class as plain JSON object only if It can be casted to `IDictionary<string, string>` or `IDictionary<string, object>`. 

I've just fixed it in **SimpleJson.cs** but don't know what to do with it. That repo seems dead. The latest release was 4 years ago. Do you have any suggestions?

However, It's nasty but you could use `Dictionary<string, object>` instead of `Dictionary<string, Small>` as a workaround.

**Comment by alexeyzimarev** [comment] 2020-01-07 16:20
Here is the template message concerning JSON serialization.

We are closing tickets that concern issues with JSON serialization after the 106.10.0 release, which includes new packages to support serialization using `NewtonsoftJson`, `Utf8Json` and `System.Text.Json`.

Most certainly, your issue will be resolved by using one of those serializers. Don't forget to check the serialization options, which can affect the ability to deserialize your request on the server-side or deserialize the response.

Please refer to the [updated documentation](http://restsharp.org/usage/serialization.html#default-serializers) about serialization.

**Closed** 2020-01-07 16:21 UTC
