### ISSUE TITLE
Deserialization error when trying to deserialize list of enums where an enum value returned in response does not exist

### ISSUE THREAD

**Issue by JohnnyV1** [restsharp/RestSharp#670] opened 2015-04-08 06:14 UTC
I noticed that if I am deserializing an object that contains an enum property, that property will be the first enum value in the enumeration if the response contains a value that is not known to the REST client deserializer.  I think that is good behavior because I usually put Unknown as the first value in enum types that go over the wire.

As an example
```c#
    public enum Values
    {
        Unknown,
        Value1,
        Value2,
        Value3
    }
```
However, If I have an object with `IEnumerable<Values>` as a property and if a list came over the wire with Value4 in it, an error is thrown and deserialization fails for the entire object.  Basically I cannot add additional enum values on the server because I may break existing clients.  Can this be changed to return the first enum value when an item in an enum list cannot be deserialized just like having an enum property on the object itself?

**Comment by kondaskondas** [comment] 2015-04-24 16:32
Give your enum values an integer value eg:
` public enum Values
{
Unknown = 0,
Value1 = 1,
Value2 = 2,
Value3 = 3
}
`
Then when the deserializer tries to assign an unknown value would be 0, if it tries to parse a value by a string it will throw. Or you can send an IEnumerable<int> and convert them to Values on your client (Simple solution).

You can check and do tests if you clone/download the repository and run this test:
Project: jsonenums
File: JsonTests.cs
Test: Can_Deserialize_Various_Enum_Values

Modify the jsonenums.txt and include and unknown value, you can see it will fail to parse an unknown string word but if its an integer it will get you the default value.
Can_Deserialize_Various_Enum_Values

**Comment by kondaskondas** [comment] 2015-04-24 17:51
[Pull request](https://github.com/restsharp/RestSharp/pull/681)

**Comment by JohnnyV1** [comment] 2015-04-27 03:46
@kondaskondas I tried being explicit in assigning values but that does not seem to be working.  Just to be clear this problem only manifests itself when the enum value that cannot be deserialized is from a list.  I understand that I can return an IEnumerable<int> and just process that further and I may eventually do that.

I created an example repository which shows the problem.  There are two projects both Client and Server.  The Server project is a WebApi project that sends down a list of enums and the Client project deserializes the request.  The Client project also contains 1 Test where the actual rest call will be made.
https://github.com/JohnnyV1/RestSharpListDeserializationProblem

**Comment by hallem** [comment] 2015-04-30 02:12
@JohnnyV1 I'm going to have to look into this behavior a little more.  I don't think any default value should be selected when it can't find the value, it should return an error because things don't match.  Let me see how the code is structured and see what some of the other serialization libraries do for this case.

**Comment by JohnnyV1** [comment] 2015-05-03 22:49
@hallem Right now there are two different behaviors when deserializing enum values which do not exist when an enum type is a property on the POCO vs. having a list of enum values of a certain type on the POCO.  The former does not throw an error and selects the default value while the latter throws the error.  Its the fact that there are two different behaviors that I think this is more of a bug then a feature request.

**Comment by hallem** [comment] 2015-05-04 05:07
@JohnnyV1 If you think about how C# implements an enum (as an integer) then the behavior you're seeing makes sense.  A list cannot have a default value where as a single integer or enum can.  Let me see how the JSON.NET library handles your case and I'll see what I can do from there.

**Comment by hallem** [comment] 2015-08-05 00:22
not a bug, closing it

**Closed by hallem** 2015-08-05 00:22 UTC
Labels: feature-request, inquiry
