### ISSUE TITLE
Exception still handled although RestClient.FailOnDeserialization is set

### ISSUE THREAD

**Issue by SvenManier** [restsharp/RestSharp#1334] opened 2019-07-12 10:43 UTC
## Expected Behavior
When RestClient.FailOnDeserialization is set to true and an exception occurs during deserialization an exception is expected to be thrown by RestClient.Get\<T\>(...)

## Actual Behavior
The exception is caught by RestSharp and given in the result

## Steps to Reproduce the Problem

  1. Set a custom Deserializer with RestClient.UseSerializer(...)
  2. Let it throw an exception (for example by explicit throw in the deserialization method)
  3. The exception is caught by RestSharp

## Specifications

  - Version: 106.6.9
  - Platform: Windows 10
  - Subsystem: ?

See: https://stackoverflow.com/questions/56966983/exception-not-caught-when-thrown-by-restsharp

**Comment by alexeyzimarev** [comment] 2019-07-12 11:23
I guess it is not an issue, right @SvenManier ?

**Comment by SvenManier** [comment] 2019-07-12 11:33
Its not? From your answer I expected to have a different behaviour

> It is still possible to tell RestSharp to throw on deserialisation if you assign the FailOnDeserialization property of the RestClient instance to true.

Or do I have a wrong interpretation?

**Comment by alexeyzimarev** [comment] 2019-07-12 11:34
Ok, so it was not the VS setting? You still don't get to your catch block?

**Comment by SvenManier** [comment] 2019-07-12 11:44
Correct. The "Exception User-Unhandled" was because of the Checkbox in VS. However the exception is still catched by RestSharp and my `try{...}catch(...)` still catches nothing

**Comment by alexeyzimarev** [comment] 2019-07-12 12:06
You are right. `FailOnDeserialization` only indicates that we return an error response. We never throw on deserialisation failure. I can quite easily add it.

**Comment by alexeyzimarev** [comment] 2019-07-12 12:12
The issue is closed by my commit but the version will be published a bit later when I figure out what is wrong with AppVeyor.

**Closed** 2019-07-12 12:11 UTC
