### ISSUE TITLE
Why RestClient must contain a value for BaseUrl

### ISSUE THREAD

**Issue by ChenJasonGit** [restsharp/RestSharp#775] opened 2015-10-31 05:41 UTC
I think somesone and me not want to set "BaseUrl" because multi difference url in one site;

**Comment by hallem** [comment] 2015-11-02 17:58
If you can provide a valid use case for not requiring a base url on the client I'll see what I can do.  No promises.  Also, just to make sure it's clear, this may or may not be possible without heavy changes I haven't looked yet so if it will require a big change than it will most likely not happen for a while if at all.

**Comment by stanac** [comment] 2017-05-09 12:17
A valid use case could be that we are calling multiple APIs where one of them have only one endpoint. There is a workaround of course, but it would be nice if we could just pass single URL instead of splitting that single URL to base URL and relative URL.

**Comment by alexeyzimarev** [comment] 2017-10-25 18:43
Duplicate of #625

**Closed by alexeyzimarev** 2017-10-25 18:43 UTC
Labels: feature-request, inquiry

**Comment by roblapp** [comment] 2018-03-30 16:57
This is really inconvenient. Enough so that I am considering just going with HttpClient.

**Comment by Gaspa79** [comment] 2018-09-05 14:57
A valid usecase is that you can have a cookie for a top level domain and have to use the cookie in different subdomains. I want to use the client cookiecontainer. I ended up changing the baseurl every time instead of just creating requests with different urls.
