### ISSUE TITLE
Compilation error CS1545 Property, indexer, or event 'RestResponseBase.IsSuccessful' is not supported by the language

### ISSUE THREAD

**Issue by Myster** [restsharp/RestSharp#1779] opened 2022-03-10 03:42 UTC
**Description**
When compiling a project targeting .NET Framework 4.7.2
I get these compilation errors: 

> Error	CS1545	Property, indexer, or event 'RestResponseBase.IsSuccessful' is not supported by the language; try directly calling accessor methods 'RestResponseBase.get_IsSuccessful()' or 'RestResponseBase.set_IsSuccessful(?)'	Website	
> Error	CS1545	Property, indexer, or event 'RestResponseBase.StatusCode' is not supported by the language; try directly calling accessor methods 'RestResponseBase.get_StatusCode()' or 'RestResponseBase.set_StatusCode(?)'	Website	

From this code:
```
		public async Task<T> ExecutePostAsync<T>(RestRequest request)
		{
			LogHelper.Info(GetType(), request.Resource);
			var response = await _client.ExecutePostAsync<T>(request, CancellationToken.None);
			if (response.ResponseStatus != ResponseStatus.Completed)
			{
				throw new PunchoutException(
					$"Request failed to complete when calling {request.Resource}");
			}

			if (!response.IsSuccessful)
			{
				throw new PunchoutException(
					$"HTTP status code {response.StatusCode} returned when calling {request.Resource}");
			}

			if (response.Data == null)
			{
				throw new PunchoutException(
					$"No Data returned when calling {request.Resource}");
			}

			return response.Data;
		}

```

**Versions**
 - OS: Windows 10
 - .NET version: .NET Framework 4.7.2
 - Version: 107.3.0

**Comment by alexeyzimarev** [comment] 2022-03-10 08:35
Duplicate of https://github.com/restsharp/RestSharp/issues/1736

**Closed by alexeyzimarev** 2022-03-10 08:35 UTC
Labels: bug
