### ISSUE TITLE
JsonDeserializer does not respect timezone info on parsing

### ISSUE THREAD

**Issue by vk5880** [restsharp/RestSharp#668] opened 2015-03-31 16:56 UTC
Value '2015-03-30T04:00:00Z' parsed to DateTimeOffset model property with local timezone. It must be parsed with zero time zone.

**Comment by viruscamp** [comment] 2015-05-21 02:33
I have find the cause, see #692

**Comment by alexeyzimarev** [comment] 2017-12-24 12:07
This is fixed by #708

**Closed by alexeyzimarev** 2017-12-24 12:07 UTC
Labels: accepted, bug

**Comment by alexeyzimarev** [comment] 2017-12-24 13:24
SimpleJson works this way. Use alternative serialisers to make it work properly.
