### ISSUE TITLE
Question: Is UrlSegment encoding new?

### ISSUE THREAD

**Issue by LordMike** [restsharp/RestSharp#707] opened 2015-06-25 10:09 UTC
Hi,

I'm using v. `104.4.0`, and I've just discovered that something that used to work no longer works. We code up against an API that uses method names with /'s in them in the URL, and we found that Restsharp accepted /'s in UrlSegments - so we used this (for 1+ years). 

But just now (can't remember if I updated Restsharp), UrlSegments are encoded?

I found this PR from 2011, #104, but it seems a bit farfetched that it just now should have come into effect - so I'm wondering, is it at all possible to not url-encode, or should I find an alternative?

**Comment by LordMike** [comment] 2015-06-25 10:21
Addendum. I've found that it works in one version of my library, but int another branch it doesn't. The difference between the branches is supposed to be whether they use async methods or not (works in synchronous, does not in asynchronous). 

Unfortunately the async branch has been long running, so it's hard to pinpoint a specific difference.

Both branches use `v104.4.0`

**Comment by LordMike** [comment] 2015-06-25 10:44
It seems to me in the code, that whichever path I take (`Execute ` or `ExecuteTaskAsync`), you always end up calling `BuildUri` which performs `StringExtensions.UrlEncode( ... )` on all `UrlSegment` parameters.

I downloaded the source for 104.4.0, and I stepped through it. It turns out that the final `new Uri(assembled)` makes everything "good" again, by converting `%2F` to `/`. Is this intentional?

Maybe `Uri` changed its behaviour.

**Comment by LordMike** [comment] 2015-06-25 10:48
Yup. If I change my `master` branch from .NET 4.0 to .NET 4.5, it stops working. `Uri` changed its behaviour.

**Comment by hallem** [comment] 2015-06-26 15:46
@LordMike this is quite an interesting scenario.  can you provide a code sample or gist that illustrates this?  I'd love to look at it more since it's a behavior change.  When I added support for the newer frameworks I wasn't aware of the change in URI behavior.  I'd like to see if I can change this to make the behavior consistent.

**Comment by LordMike** [comment] 2015-06-26 16:24
It should be a pretty straightforward operation, if you simply switch from 4.5 to <4.5.

The previous link from Microsoft pits some detail to the change, else write back and I'll see what I can create later this evening.

**Comment by hallem** [comment] 2015-08-05 00:13
An example would be great

**Comment by mike-csis** [comment] 2015-08-05 09:38
Use the following code in both .NET 4.0 and 4.5. 

    static void Main(string[] args)
    {
        RestClient cl = new RestClient("https://github.com/");
        
        RestRequest req = new RestRequest("/restsharp/RestSharp/{segment}");
        req.AddUrlSegment("segment", "issues/707");
        
        IRestResponse res = cl.Get(req);
        
        Console.WriteLine("Got response code " + res.StatusCode + " for " + res.ResponseUri);
    }

In .NET 4.0, it outputs: `Got response code NotAcceptable for https://github.com/restsharp/RestSharp/issues/707` 
In .NET 4.5, it outputs: `Got response code NotFound for https://github.com/restsharp/RestSharp/issues%2F707`

Note: The 4.5 behaviour is the intended one.

**Comment by alexeyzimarev** [comment] 2017-12-24 12:59
Since the .NET 4.0 support is deprecated, I am closing this issue as no longer relevant.

**Closed by alexeyzimarev** 2017-12-24 12:59 UTC
Labels: investigate

**Comment by jeff-pang** [comment] 2020-05-29 09:11
The exact this happened to me now.

```C#
string baseUrl = "http://somebaseurl";
var client = new RestClient(baseUrl).UseNewtonsoftJson();
string segment = "something/tmp";
var request = new RestRequest("/hello/{segment}}")
    .AddParameter("segment",segment, ParameterType.UrlSegment);

var res = await client.ExecuteGetAsync<JToken>(request);
Console.Write(res.ResponseUri.ToString())
```

output: `http://somebaseurl/hello/something%2Ftmp%7D`

**Comment by alexeyzimarev** [comment] 2020-05-31 12:08
@jeff-pang that is by design. We expect the segment parameter to be a parameter, so it must be encoded. You don't supply a parameter as such, it doesn't follow the parameter spec.
