### ISSUE TITLE
ResponseStatus is Error when response is 404 NotFound

### ISSUE THREAD

**Issue by mwinder** [restsharp/RestSharp#837] opened 2016-04-21 07:56 UTC
Use RestClient.Execute<TResult>(...) to perform a GET that results in a 404.
The IRestResponse<TResult> that comes back has ResponseStatus = Error.
    - The ErrorException property has the message "Invalid JSON string".
    - The Data property response = null.

Perform the same request with the (non-generic) RestClient.Execute(...).
The IRestResponse has ResponseStatus = Complete

I appears that it is failing to deserialize the response into the typed model (TResult).
In this particular API resource returns a Content body of " " (single space character), not sure if it should be a completely empty body.

I would have expected the ResponseStatus in both cases to be Completed - the request succeeded, there where no transport errors.

**Comment by behoyh** [comment] 2016-05-24 12:36
I have set up a Windows Forms App to test. Could you provide more details about this issue? I'm not sure what you mean by "non-generic"

**Comment by mwinder** [comment] 2016-05-25 08:41
By "non-generic" I meant the Execute method on RestClient that doesn't take a generic parameter:

`IRestResponse Execute(IRestRequest request);`

versus:

`IRestResponse<T> Execute<T>(IRestRequest request) where T : new();`

If it helps I ended up working around the issue by writing an extension method on IRestResponse that uses Json.NET to deserialize the Content property:
```
public static TResult Content<TResult>(this IRestResponse response)
{
    return JsonConvert.DeserializeObject<TResult>(response.Content);
}
```

I could then use the "non-generic" Execute method to make my request and get a typed response with my extension method:

```
var resp = client.Execute(new RestRequest("some/resource"));

if (resp.ResponseStatus != ResponseStatus.Completed) { // Check whether request completed
     //Handle error
}

if (resp.StatusCode == HttStatusCode.NotFound) { // Check for 404
     //Handle 404
}

var result = resp.Content<SomeResult>();
```

Performing the same steps with the "generic" Execute:

```
var resp = client.Execute<SomeResult>(new RestRequest("some/resource"));

if (resp.ResponseStatus != ResponseStatus.Completed) {
     //This is reached even for 404 - I presume because of a failure during deserialization
}

//Handling 404 here isn't possible be cause it appears the request did not complete...
if (resp.StatusCode == HttStatusCode.NotFound) {
    //Handle 404
}

var result = resp.Data; // Data is null
```

**Comment by simonob** [comment] 2016-06-16 12:12
I'm getting this same problem using v105.2.3, so have changed my Execute<> calls to Execute and used the suggestion above which has resolved the issue.

The issue appears to be due to the content from the server for an HTTP 500 response being a chunk of HTML, which can't be deserialized into my type using the JSON serializer and therefore I'm guessing the ResponseStatus is set to Error as the deserialization failed.

The current documentation suggests that the ResponseStatus is only set for network/connectivity-related errors, and not deserialization errors.

For what it's worth, my proposal would be that the Data property throws an exception if deserialization fails, rather than changing the ResponseStatus from Completed to Error (although this may represent a breaking change for those expecting it to work as it does currently).

**Comment by benbward** [comment] 2018-03-21 22:01
Still open?  Is this going anywhere?

**Comment by alexeyzimarev** [comment] 2018-03-22 19:49
I think it should be fixed. The suggestion of @simonob sounds very reasonable. Many apps return crappy responses that we cannot deserialise, this is quite normal.

**Comment by alexeyzimarev** [comment] 2019-01-20 20:37
Ok, that it in fact by design. I added an option to return Completed when deserialization fails. For the backward compatibility, I must keep current behaviour as-is, but if you set `RestClient.FailOnDeserializationError` to false in the next version, you will get it sorted.

**Closed by alexeyzimarev** 2019-01-20 20:37 UTC
Labels: IMPORTANT, accepted, investigate

**Comment by forbjok** [comment] 2020-01-29 14:13
Out of curiousity, what was the reason for going with this behavior?
To me, it seems like the most logical behavior in the case where a request successfully completes and receives a status code from the server, but fails to be deserialized locally, would be to have IsSuccessful be false and ResponseStatus = Completed.

The way it is currently, there is as far as I can tell no way to tell from looking at either of those properties, whether the request failed to get a response from the server, or completed successfully but failed to deserialize. They basically both seem to indicate the same thing, making one of them redundant.

**Comment by Zunair** [comment] 2023-02-02 08:32
I had a similar issue - so I tested the same get request on PostMan.
Get request worked from browser but not on PostMan and from RestSharp.
Compared the request headers - found that Accept-Language was required for api(phpMyFaq) I was using.

Added the missing header in the request - all looks good on PostMan and RestSharp.
