### ISSUE TITLE
Question: Does this library work if used as a singleton instance stored in IOC/DI?

### ISSUE THREAD

**Issue by reloaded** [restsharp/RestSharp#1065] opened 2018-01-12 01:10 UTC
If I have an object that wraps RestSharp and store the wrapper object in IOC will the IAuthenticator be shared across all HTTP requests? Does it make sense to have one instance of RestClient to conserve resource usage or should I instantiate a new AuthenticationRestClient for each HTTP request that needs it?

Here's my wrapper object:

```
    /// <summary>
    /// <see cref="AuthenticationRestClient"/> streamlines API calls against the Authentication microservice
    /// (aka BC/Bounded Countext) using concrete request and response objects. Pass it an API endpoint URI
    /// when contructing a new instance of <see cref="AuthenticationRestClient"/> and you're on your way to
    /// making API calls.
    /// </summary>
    /// <remarks>
    /// It's recommended to inject <see cref="AuthenticationRestClient"/> into the application IOC/DI
    /// as a singleton instance to alleviate extra resource usage by reducing the number of underlying REST
    /// client instances.
    /// </remarks>
    public class AuthenticationRestClient : IAuthenticationApi
    {
        // ReSharper disable once PrivateFieldCanBeConvertedToLocalVariable
        private readonly Uri _uri;
        private readonly RestSharp.RestClient _restClient;

        /// <summary>
        /// Initializes a new <see cref="AuthenticationRestClient"/> and issues requests to the host 
        /// defined in the given <see cref="Uri"/>.
        /// </summary>
        /// <param name="uri">A <see cref="Uri"/> object configured with HTTP/HTTPS URI scheme and an
        /// authority. Note: No other information from <see cref="Uri"/> is used (e.g. path and query
        /// strings are not used at this time).</param>
        public AuthenticationRestClient(Uri uri)
        {
            _uri = uri;
            _restClient = new RestSharp.RestClient(_uri);
        }

        /// <summary>
        /// Initializes a new <see cref="AuthenticationRestClient"/> and issues requests to the 
        /// given <see cref="hostname"/>.
        /// </summary>
        /// <param name="hostname">The hostname to connect to. Must include a HTTP/HTTPS URI scheme and
        /// an authority. Note: No other information from the URI is used (e.g. path and query strings
        /// are not used at this time).</param>
        public AuthenticationRestClient(string hostname)
        {
            _uri = new Uri(hostname);
            _restClient = new RestSharp.RestClient(_uri);
        }

        public Task<GetUserBasicDto> GetUserBasic(GetUserBasicRequest request)
        {
            // Will this JwtAuthentictor with a specific user's access token be used by all other HTTP connection?
            _restClient.Authenticator = new JwtAuthenticator(request.AccessToken);

            var t = new Task<GetUserBasicDto>(() =>
            {
                var restRequest = new RestRequest("/api/v1/authentication/user/{uid}", Method.GET);
                restRequest.AddParameter("uid", request.UserId, ParameterType.UrlSegment);
                restRequest.AddHeader("FID", request.FID.ToString());

                var response = _restClient.Execute<GetUserBasicDto>(restRequest);

                return response.Data;
            });

            t.Start();

            return t;
        }
    }
```

Here's how I plan to add it to IOC:

```
public void ConfigureServices(IServiceCollection services)
{
    services.AddSingleton<IAuthenticationApi, AuthenticationRestClient>();
}
```

## Specifications

  - Version: 106.2.1
  - Platform: .NET Core 2.x (Windows & Linux)
  - Subsystem: N/A?

**Comment by alexeyzimarev** [comment] 2018-01-16 15:34
Duplicate of https://github.com/restsharp/RestSharp/issues/951

**Closed by alexeyzimarev** 2018-01-16 15:34 UTC
