### ISSUE TITLE
OAuth1Authenticator doesn't work anymore I guess

### ISSUE THREAD

**Issue by fightlikeagirl** [restsharp/RestSharp#1197] opened 2018-10-16 06:37 UTC
I used to post statuses with this code before but it gives me authentication error now so I think it can be about Restsharp. How can I solve this ?  
   static void Main(string[] args)
        {
            var t = new Twt();
            t.UpdateStatus("IT's finally friday",cs,cts,us,uts);  //Credentials 
        }
 public void UpdateStatus(string status,string key,string secret,string token,string tokenSecret)
        {
            var request = new RestRequest("/1.1/statuses/update.json", Method.POST);

            request.AddQueryParameter("status", status);

            Client.Authenticator = OAuth1Authenticator.ForProtectedResource(key, secret, token, tokenSecret);

            var response = Client.Execute(request);

            var content = response.Content;
        }

Request url was http://api.twitter.com/

**Comment by alexeyzimarev** [comment] 2018-10-20 11:42
Which version are you using now? Have you tried 106.3, 106.2? Please help me to isolate this issue since you have the code ready.

**Comment by alexeyzimarev** [comment] 2018-10-20 14:00
Duplicate of #1188?

**Comment by alexeyzimarev** [comment] 2018-12-29 21:33
We have applied some fixes in 106.6, please reopen this issue if it still fails.

**Closed by alexeyzimarev** 2018-12-29 21:33 UTC
