### ISSUE TITLE
Support for HttpMessageHandler to allow in-memory web api

### ISSUE THREAD

**Issue by juliencousineau** [restsharp/RestSharp#932] opened 2017-02-24 21:16 UTC
Like HttpClient does with 

```
HttpConfiguration config = new HttpConfiguration();

WebApiConfig.Register(config);

_server = new HttpServer(config);

_client = new HttpClient(_server);
```

It can be really helpful if RestSharp can support like HttpClient!

**Comment by shyamgudi** [comment] 2018-04-27 19:56
Any update on this? This would be helpful to have something like this in RestSharp

**Comment by alexeyzimarev** [comment] 2018-04-27 20:30
Of course. If you need it - please do it.

**Comment by alexeyzimarev** [comment] 2019-01-21 21:38
Duplicate of #747

**Closed by alexeyzimarev** 2019-01-21 21:38 UTC
